[package]
name = "rekordbox-spotify-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
xml = "1.2.0"
roxmltree = "0.20"
chrono = "0.4.42"
rspotify = { version = "0.14", features = ["env-file"] }
tokio = { version = "1", features = ["full"] }
axum = "0.7"
tower = "0.4"
dotenv = "0.15"